[acknowledgements]
== Acknowledgements

[[book_start]]
[role="row"]
You see four names on this book cover. But this book a product of more than four people. It's a product of our company - Farata Systems.

In particular, we'd like to thank Alex Maltsev, who was playing a role of Jerry-The-Designer starting from Chapter 3 and onward. Alex created all UI prototypes for the sample Web application "Save Sick Child" that is designed, re-designed, developed, and re-developed several times in this book. He also developed a number of code samples for the book and all CSS files.

Our big thanks to Anton Moiseev who developed the Ext JS and Sencha Touch versions of our sample application. 

Our hats off to the creators of the http://asciidoc.org/[Asciidoc text format] - the drafts of this book were prepared in this format with the subsequent generation of PDF, EPUB, MOBI, and HTML documents. 

In our sample application we've used two images from the http://www.istockphoto.com/[iStockPhoto] collection: the smiling boy by the user _jessicaphoto_ and the logo by the user _khalus_. Thank you, guys!

Finally, our thanks to the O'Reilly editors for being so patient while we were trying to hit lots of moving and evolving targets that together represent the universe known as HTML5.