[colophon]
= Colophon

The animal on the cover of _Enterprise Web Development_ is a roseate spoonbill (_Platalea ajaja_), and is a resident breeder in South America, often found east of the Andes, around the coast of Central America, the Caribbean, Mexico, and the Gulf Coast. The roseate spoonbill was found to be a close relative of yellow-billed spoonbills, both descended of the other four spoonbill species. 

With a wingspan averaging around 47–52 inches, these spoonbills are often about 28–34 inches long. Immature birds have white, feathery heads with pale pink plumage and a yellow or pinkish bill. Adults have a bare greenish head that turns golden when breeding with a white neck, back, and breast. The rest of their bodies are a deep pink, aside from a grey bill. Similar to the American flamingo, the pink color of the roseate spoonbill is diet-derived, coming mostly from the carotenoid pigment canthaxanthin. 

This species feeds by wading through shallow fresh or coastal waters, swinging its bill from side to side. They are gregarious and often feed in groups. Its spoon-shaped bill helps to sift through the mud for crustaceans, aquatic insects, frogs, newts, and very small fish. 

They nest in shrubs or trees, and lay from two to five whitish eggs with brown markings. There is not much information available about the roseate spoonbill's predators, however, nestlings are sometimes killed by turkey vultures, bald eagles, raccoons, and fire ants.

The cover image source is unknown. The cover fonts are URW Typewriter and Guardian Sans. The text font is Adobe Minion Pro; the heading font is Adobe Myriad Condensed; and the code font is Dalton Maag's Ubuntu Mono.
