Enterprise Web Development: From Desktop to Mobile
--------------------------------------------------

This ia a home of the new book (work in progress) «Enterprise Web
Development. From Desktop to Mobile». There are four co-authors of this
book: Yakov Fain, Victor Rasputnis, Viktor Gamov, and Anatole
Tartakovsky. The book is released under a Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported
http://creativecommons.org/licenses/by-nc-sa/3.0/[license] meaning you
can both get a copy of the book for free or help to further improve it.
This book will be printed and available for purchase via
http://oreilly.com/[O’Reilly Media]. Readers will have an option of
purchasing this book in a number of digital formats.

Table Of Contents
~~~~~~~~~~~~~~~~~

*
link:EnterpriseWebBook/blob/master/0_Introduction/Introduction.mdown[Introduction]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* Part 1. Desktop
^^^^^^^^^^^^^^^
**
link:EnterpriseWebBook/blob/master/1_Desktop/01_html/ch1_html.mdown[Ch1.
HTML5 and its New APIs]
**
link:EnterpriseWebBook/blob/master/1_Desktop/02_JavaScript/ch2_advancedjs.mdown[Ch2.
Advanced Intro to JavaScript]
**
link:EnterpriseWebBook/blob/master/1_Desktop/03_Mockup/ch3_mokup.mdown[Ch3.
Mocking Up the ``Save a Child'' Web Site]
** link:#ch4[Ch4. Using Ajax and JSON]
**
link:EnterpriseWebBook/blob/master/1_Desktop/05_Testing_JavaScript/Chapter_5_Test-Driven_Development_with_JavaScript.mdown[Ch5.
Test-Driven Development with JavaScript]
** link:#ch6[Ch6. «Save a Child» with JQuery framework]
** link:#ch7[Ch7. «Save a Child» with Ext JS framework]
**
link:EnterpriseWebBook/blob/master/1_Desktop/08_Websockets/Chapter_8_Replacing_HTTP_With_WebSockets.mdown[Ch8.
Replacing HTTP with WebSockets]
** link:#ch9[Ch9. Securing Web Applications]
** link:#ch10[Ch10. Large Scale JavaScript Projects]
* Part 2. Mobile
^^^^^^^^^^^^^^
** link:EnterpriseWebBook/blob/master/2_Mobile/11_responsive.mdown[Ch11.
Responsive Design: One Site Fits All]
** link:#ch12[Ch12. «Save a Child» With JQuery Mobile]
** link:#13[Ch13. «Save a Child» with Sencha Touch]
** link:#14[Ch14. Hybrid Applications: HTML + Native API]

Using Ajax and JSON
-------------------

After explaining the JSON data format we’ll deploy Save a Child under
the remote Tomcat server on one of our servers. We’ll also provide the
instructions on installing Tomcat on the local machine for those readers
who want to do it. Then goes the explanation of the AJAX way of
retrieving data from the remote server without the need to refresh the
entire page. In the final version of the Web site the data feed will be
organized by a Java program deployed under a Java EE server – we’ll use
Oracle’s GlassFish 4.0 for being the leader in implementing all the
latest Java EE specifications.

«Save a Child» with JQuery framework
------------------------------------

In this chapter we’ll start introducing JQuery framework to Save a Child
code developed in chapters 2-5. While this chapter won’t have a formal
tutorial on the JQuery framework, we’ll briefly explain its basics and
each component that’ll be used in Save a Child. By the end of this
chapter the reader has a working version of Save a Child site built
using HTML, JavaScript, CSS, JSon, Ajax, and JQuery framework.

«Save a Child» with Ext JS framework»
-------------------------------------

In this chapter we’ll use some of the code from ch 2-5, but this time
we’ll use the Sencha’s Ext JS framework. The reader will learn the
principles of building Web sites with Ext JS. We’ll demo the use of our
own open source generator Clear Data Builder that can generate the EXT
JS code based on Java classes. By the end of this chapter the reader
will have working version of the Save a Child Web site. We’ll also
compare the pros and cons of its Ext JS and JQuery’s versions.

Securing Web Applications
-------------------------

This chapter will add authentication and authorization features for the
users Save a child. They will be able to login to this Web site and
perform different actions according to their role.

The Save a Chile site is a rather small Web project. But in the
enterprise world, lots of applications have a lot larger code base. In
this chapter we’ll give an example of how to build modularized Web
applications that can load the code on as needed basis. We’ll also give
an example of how to organize the data exchange between different
modules in a loosely coupled fashion.

«Save a Child» With JQuery Mobile
---------------------------------

This chapter will demonstrate how to build the mobile version of Save a
Child using JQuery Mobile framework.

«Save a Child» with Sencha Touch
--------------------------------

This chapter will demonstrate how to build the mobile version of Save a
Child using the Sencha Touch framework.

Hybrid Applications: HTML + Native API
--------------------------------------

This chapter explains how to add the bridge HTML and native mobile API
with the Phone GAP framework. It’ll add the GPS service to the mobile
version of ``Save a Child''.
