My notes:

== Chapter 7

I don't think that we need to move Grunt to any chapter.

* p. 313 V: we're giving an explanation through example. 
* p. 315 banderson:  Here's an example: V: 
* p. 316 banderson: Also mention Universal Module Definition here, briefly. - V: mentioned in dedicated section. Also I would prefer to keep sections as is (without additional word Option X)
* p. 321 banderson: We need a new paragraph. V: new paragraph to explain in code explanation? I didn't catch that.
* p. 322 V: distinction b/w CJS and AMD provided later in this section
* p. 325 V: I agree with code comments. We need to use === in most cases
* p. 326 V: converted sidebar to subsection
* p. 329 V: there is no need to add summary in between of chapter. Summary of chapter contains required overview.
** No. because we develop *web* application, we're going to use AMD approach only.
** extensive overview follows later in this section.
** yes, it's a good place for this note.
* p. 332 V: we have same text at the beginning of this section
* p. 333 V: OR we can have it as subsection
* p. 334 V: no we don't need sudo if we installed node via homebrew. Also, there is no sudo on windows.
* p. 338 V: AMD is a standard. There is no such thing as AMD modules for RequireJS
* p. 346 V: I don't understand the questions?